### ISSUE TITLE
ファイルアップロードサイズ30MB制限の変更方法について検討のお願い

### ISSUE THREAD

**Issue by tnkmsh** [Implem/Implem.Pleasanter.NetCore#10]
Pleasanterが非常に活用しやすいツールと考えて社内での導入を進めていますが、CentOS7上でPleasanterを構築してWebページから30MBを超えるファイルを添付ファイル欄にアップロードしようとすると413エラーが出ました。サーバの設定（nginxの設定ファイルやPleasanter内のapp.config）の設定も確認しましたが、設定箇所が見当たりません。
WindowsでIISを用いる場合はPleasanterのWebマニュアルにもあります通りIISの設定変更で対応できますが、CentOSのようなLinuxでPleasanterを実行する場合はIISにあたるKestrelのWebHostを起動していて、このWebHostへの設定がコマンドラインオプションだけでは設定できなかったため、現在は以下のようにImplem.Pleasanter.NetCoreプロジェクトのProgram.csを直接修正し、build.shを実行してビルドすることで対処しております。

Program.csのCreateWebHostBuilder関数（修正前）

        public static IWebHostBuilder CreateWebHostBuilder(string[] args)
        {
            var config = new ConfigurationBuilder()
                .AddCommandLine(args)
                .Build();
            var webHost = WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
            return webHost;
        }

Program.csのCreateWebHostBuilder関数（修正後）

        public static IWebHostBuilder CreateWebHostBuilder(string[] args)
        {
            var config = new ConfigurationBuilder()
                .AddCommandLine(args)
                .Build();
            var webHost = WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseKestrel(options =>
                {
                    options.Limits.MaxRequestBodySize = 5000000000; // 5GB
                });
            return webHost;
        }

ただ、この修正方法はバージョンアップ等についていけないですので、可能でしたら
https://github.com/dotnet/aspnetcore/issues/4765
に書かれているような形でappsettings.jsonに以下のように追記することでWebHostに設定できるように拡張していただけると嬉しいです。お手数をおかけしますが、ご検討をお願いします。

    "Kestrel": {
        "Limits": {
              "MaxRequestBodySize": 10000000000
        }
    }

**Comment by pierre3** [comment]
ご提案ありがとうございます。
v1.1.0.1 以降で以下のように変更いたしました。

commit  : https://github.com/Implem/Implem.Pleasanter.NetCore/commit/a9cd38c0a981d071df16efb80cbca57b94c9c207

- MaxRequestBodySizeのデフォルト値をlong.MaxValue としました。
- ご提案頂いたように appsettings.json からKestrelOptions の設定値を取得可能としました。


最新版をインストールの上、ご確認いただけますでしょうか。

**Comment by tnkmsh** [comment]
確認いたしました。ご対応いただきまして誠にありがとうございました。
