### ISSUE TITLE
1.3.25.3 にて Azure AD との SAML 認証の設定後に 500 が発生

### ISSUE THREAD

**Issue by tatsuyasenbom** [Implem/Implem.Pleasanter.NetCore#106]
# 概要
* 以下`環境`にて標題の現象が発生しました。
* `Azure AD`側は以下記事を参考に設定を行いました。
    * [公式 - プリザンターでSAML認証を利用する](https://pleasanter.org/manual/saml)
    * [Qiita - プリザンター(.NET Core版)でSAML認証する](https://qiita.com/tatsuya_info/items/19c33558a853501e68b0)
    * [note - プリザンター.NET Core版×AppServiceでSAML認証してみる（SAML設定編）](https://note.com/goetan/n/nb1f8692b7608) 
* お手数をおかけしますが、ご確認いただければ幸いです。

# 環境
* Windows Server 2016
* Microsoft SQL Server 2016
* IIS

# 現象
1. Implem.Pleasanter\App_Data\Parameters\Authentication.json

	```json
	{
	    "Provider": "SAML",
	    "ServiceId": null,
	    "ExtensionUrl": null,
	    "RejectUnregisteredUser": false,
	    "LdapParameters": [
	        {
	            "LdapSearchRoot": null,
	            "LdapSearchProperty": "sAMAccountName",
	            "LdapSearchPattern": null,
	            "LdapLoginPattern": null,
	            "LdapAuthenticationType": null,
	            "NetBiosDomainName": null,
	            "LdapTenantId": 1,
	            "LdapDeptCode": null,
	            "LdapDeptCodePattern": null,
	            "LdapDeptName": null,
	            "LdapDeptNamePattern": null,
	            "LdapUserCode": null,
	            "LdapUserCodePattern": null,
	            "LdapFirstName": "givenName",
	            "LdapFirstNamePattern": null,
	            "LdapLastName": "sn",
	            "LdapLastNamePattern": null,
	            "LdapMailAddress": "mail",
	            "LdapMailAddressPattern": null,
	            "LdapSyncPageSize": 0,
	            "LdapSyncPatterns": [
	                "(&(ObjectCategory=User)(ObjectClass=Person))"
	            ],
	            "LdapExcludeAccountDisabled": false,
	            "AutoDisable": false,
	            "AutoEnable": false,
	            "LdapSyncUser": null,
	            "LdapSyncPassword": null
	        }
	    ],
	    "SamlParameters": {
	        "Attributes": {
	            "Name": "Name",
	            "UserCode": "UserCode",
	            "Birthday": "Birthday",
	            "Gender": "Gender",
	            "Language": "Language",
	            "TimeZone": "TimeZone",
	            "TenantManager": "TenantManager",
	            "DeptCode": "DeptCode",
	            "Dept": "Dept",
	            "Body": "Body",
	            "MailAddress": "{NameId}"
	        },
	        "SamlTenantId": 1,
	        "DisableOverwriteName": false,
	        "SPOptions": {
	            "EntityId": "https://my-pleasanter.work/pleasanter/Saml2",
	            "ReturnUrl": "https://my-pleasanter.work/pleasanter/Users/SamlLogin",
	            "AuthenticateRequestSigningBehavior": "IfIdpWantAuthnRequestsSigned",
	            "OutboundSigningAlgorithm": "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
	            "MinIncomingSigningAlgorithm": "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
	            "IgnoreMissingInResponseTo": false,
	            "PublicOrigin": "https://my-pleasanter.work/pleasanter-test",
	            "ServiceCertificates": []
	        },
	        "IdentityProviders": [
	            {
	                "EntityId": "https://sts.windows.net/XXXXXX-XXXX-XXXX-XXXX-XXXXXXXX/",
	                "SignOnUrl": "https://login.microsoftonline.com/XXXXXX-XXXX-XXXX-XXXX-XXXXXXXX/saml2",
	                "LogoutUrl": null,
	                "AllowUnsolicitedAuthnResponse": true,
	                "Binding": "HttpPost",
	                "WantAuthnRequestsSigned": false,
	                "DisableOutboundLogoutRequests": true,
	                "LoadMetadata": false,
	                "MetadataLocation": null,
	                "SigningCertificate": {
	                    "StoreName": "CurrentUser",
	                    "StoreLocation": "My",
	                    "X509FindType": "FindByThumbprint",
	                    "FindValue": "B850XXXXXXXXXXXXXXXXXXXXXXXXXX"
	                }
	            }
	        ]
	    }
	}
	```
2. `IIS`再起動
3. Webブラウザから`https://my-pleasanter.work/`へアクセス後`500`を確認
4. `select top 2 * from "SysLogs" order by "CreatedTime" desc;`により以下ログを確認

	| CreatedTime | SysLogId | Ver | SysLogType | OnAzure | MachineName | ServiceName | TenantName | Application | Class | Method | RequestData | HttpMethod | RequestSize | ResponseSize | Elapsed | ApplicationAge | ApplicationRequestInterval | SessionAge | SessionRequestInterval | WorkingSet64 | VirtualMemorySize64 | ProcessId | ProcessName | BasePriority | Url | UrlReferer | UserHostName | UserHostAddress | UserLanguage | UserAgent | SessionGuid | ErrMessage | ErrStackTrace | InDebug | AssemblyVersion | Comments | Creator | Updator | UpdatedTime |
	|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
	| 2022-11-15 15:15:45.413 | 4164678 | 1 | 90 | NULL | WIN-1H8MFFKK2HK:Microsoft Windows NT 10.0.14393.0 | Implem.Pleasanter | NULL | Implem.DefinitionAccessor | errors | internalservererror | NULL | GET | NULL | NULL | 3.0651 | 2916772.3684 | 14.3177 | -0.0005 | 415.4939 | 545021952 | 2221190369280 | 8180 | w3wp | 8 | https://my-pleasanter.work/pleasanter/errors/internalservererror?NoLog=1 | NULL | 127.0.0.1 | 127.0.0.1 | ja | Mozilla/5.0 (Windows NT; Windows NT 10.0; ja-JP) WindowsPowerShell/5.1.14393.4583 | 9A6021F0B6D44682BF5E2773914C986A   | Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') |    at System.Collections.CollectionBase.System.Collections.IList.get_Item(Int32 index)     at Implem.Pleasanter.Libraries.DataSources.Saml.SetSPOptions(Saml2Options options) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\DataSources\Saml.cs:line 329     at Implem.Pleasanter.NetCore.Startup.<>c__DisplayClass2_0.<ConfigureServices>b__4(Saml2Options options) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Startup.cs:line 99     at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)     at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)     at Sustainsys.Saml2.AspNetCore2.Saml2Handler.<>c__DisplayClass7_0.<InitializeAsync>b__0()     at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)  --- End of stack trace from previous location ---     at System.Lazy`1.CreateValue()     at Sustainsys.Saml2.AspNetCore2.Saml2Handler.InitializeAsync(AuthenticationScheme scheme, HttpContext context)     at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)     at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)     at Implem.Pleasanter.NetCore.Startup.Invoke(HttpContext httpContext, Func`1 next) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Startup.cs:line 338 | NULL | 1.3.25.3 | NULL | 0 | 0 | 2022-11-15 15:15:45.413 |
	| 2022-11-15 15:15:45.393 | 4164677 | 1 | 90 | NULL | WIN-1H8MFFKK2HK:Microsoft Windows NT 10.0.14393.0 | Implem.Pleasanter | NULL | Implem.DefinitionAccessor | reminderschedules | remind | NULL | GET | NULL | NULL | 4.1013 | 2916758.0502 | 5019.5001 | -0.001 | 401.5315 | 545021952 | 2221190369280 | 8180 | w3wp | 8 | https://my-pleasanter.work/pleasanter/reminderschedules/remind?NoLog=1 | NULL | 127.0.0.1 | 127.0.0.1 | ja | Mozilla/5.0 (Windows NT; Windows NT 10.0; ja-JP) WindowsPowerShell/5.1.14393.4583 | FA8A234D04B34079977360BC49B28F8E   | Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') |    at System.Collections.CollectionBase.System.Collections.IList.get_Item(Int32 index)     at Implem.Pleasanter.Libraries.DataSources.Saml.SetSPOptions(Saml2Options options) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\DataSources\Saml.cs:line 329     at Implem.Pleasanter.NetCore.Startup.<>c__DisplayClass2_0.<ConfigureServices>b__4(Saml2Options options) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Startup.cs:line 99     at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)     at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)     at Sustainsys.Saml2.AspNetCore2.Saml2Handler.<>c__DisplayClass7_0.<InitializeAsync>b__0()     at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)  --- End of stack trace from previous location ---     at System.Lazy`1.CreateValue()     at Sustainsys.Saml2.AspNetCore2.Saml2Handler.InitializeAsync(AuthenticationScheme scheme, HttpContext context)     at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)     at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)     at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)     at Implem.Pleasanter.NetCore.Startup.Invoke(HttpContext httpContext, Func`1 next) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Startup.cs:line 338 | NULL | 1.3.25.3 | NULL | 0 | 0 | 2022-11-15 15:15:45.393 |

**Comment by tatsuyaueda** [comment]
同じバージョンの手元の環境では、ほぼ同じ設定ファイルで、AADを使ったSAML認証が出来ているので環境の問題かと思います。

ログを見る限りですが、[Saml.csの329行目](https://github.com/Implem/Implem.Pleasanter.NetCore/blob/Pleasanter_1.3.25.3/Implem.Pleasanter/Libraries/DataSources/Saml.cs#L329)でIndexが範囲外という事ですので、
IDPの証明書が取得出来ないことが要因では無いかと思います。

ただ、このコメントを書いていて気づいたのですが、下記のパラメタの値が入れ替わってしまっているようです。
(自分が書いた記事もどこかからのコピペだとは思うのですが、今のところtatsuyasenbomさんと同じ設定で動いている状況です。)

```
                  "StoreName": "My",
                  "StoreLocation": "LocalMachine",
```

参考にならないかもしれませんが、証明書まわりご確認頂いてみてはどうでしょうか。

**Comment by tatsuyasenbom** [comment]
> 同じバージョンの手元の環境では、ほぼ同じ設定ファイルで、AADを使ったSAML認証が出来ているので環境の問題かと思います。
> 
> ログを見る限りですが、[Saml.csの329行目](https://github.com/Implem/Implem.Pleasanter.NetCore/blob/Pleasanter_1.3.25.3/Implem.Pleasanter/Libraries/DataSources/Saml.cs#L329)でIndexが範囲外という事ですので、 IDPの証明書が取得出来ないことが要因では無いかと思います。
> 
> ただ、このコメントを書いていて気づいたのですが、下記のパラメタの値が入れ替わってしまっているようです。 (自分が書いた記事もどこかからのコピペだとは思うのですが、今のところtatsuyasenbomさんと同じ設定で動いている状況です。)
> 
> ```
>                   "StoreName": "My",
>                   "StoreLocation": "LocalMachine",
> ```
> 
> 参考にならないかもしれませんが、証明書まわりご確認頂いてみてはどうでしょうか。

ご回答いただきありがとうございました。
ご案内いただいた内容を踏まえ再度設定を確認したところ、`Pleasanter`側に`Azure AD`側で発行された証明書をインストールした場所と`StoreName`と`StoreLocation`で指定した場所の整合性が合っていない事が原因でした。

上記の整合性を合わしたことで`SSO`による`Pleasanter`へのログイン及び`Pleasanter`側に`SSO`ユーザが自動生成される事を確認しました。

調査いただきありがとうございました。
