### ISSUE TITLE
SQLServerからPostgresqlへのマイグレーションで新規作成、更新エラー

### ISSUE THREAD

**Issue by koikoi0407** [Implem/Implem.Pleasanter.NetCore#14]
手順「プリザンターのDBをSQL ServerからPostgreSQLへ移行する」でデータ移行を行ったが、データは移行できるが、新規作成、更新(通知設定有り)時にアプリケーションエラーとなる。
Logからインデクス不正が判明したため、Postgresql側のシーケンスを確認すると全て「1」が設定されている。
以下のシーケンスを各テーブルのMAX値に変更して対応した。
Depts_DeptId_seq
Groups_GroupId_seq
Registrations_RegistrationId_seq
Users_UserId_seq
MailAddresses_MailAddressId_seq
OutgoingMails_OutgoingMailId_seq
Items_ReferenceId_seq
ExportSettings_ExportSettingId_seq
Binaries_BinaryId_seq

以上、マイグレーション時の処理見直しをお願いします。

**Comment by uchi-ta** [comment]
Issueありがとうございます。シーケンスを更新する処理を追加いたしました。
https://github.com/Implem/Implem.Pleasanter.NetCore/commit/130c93c42c0ab059236f7bed9cca3e587a42b5cb
