### ISSUE TITLE
導入手順のSQL Serverの構成について

### ISSUE THREAD

**Issue by jakenjarvis** [Implem/Implem.Pleasanter.NetCore#2]
はじめまして。Linux版が出来たのを知り、試してみたくなり、セットアップしています。
手順通り進め、ubuntu18.04にSQL Serverを構築するところまでは出来ました。
（途中、libcurl3とlibcurl4でコンフリクトが起きてしまい、正しい解決方法がわかっていませんが・・・）

WindowsPCで普通にセットアップを行い、WindowsのローカルSQL Serverへの接続でpleasanterのログイン画面を開けることを確認しました。
また、その後、WindowsPCから、ManagementStudioにて、ネットワーク越しにubuntu側SQL Serverへ接続できることは確認しました。

この状態から、このURLの手順で、
https://github.com/Implem/Implem.Pleasanter.NetCore#sql-server-を構成するlinux
この二つのファイルの扱いで、混乱してます。
・PleasanterNetCore\Implem.Pleasanter\App_Data\Parameters\Rds.json
・PleasanterNetCore\Implem.Pleasanter\App_Data\Definitions\definition_Sql.xlsm
これは、Windows側の「%SystemDrive%\inetpub\wwwroot\pleasanter」の中での作業ではないでしょうか？
そう思って、いろいろ試してみましたが、うまく動かせていません。
そこで、以下の手順であっているか確認させてください。

１．Rds.jsonを書き換える。
Windows側の %SystemDrive%\inetpub\wwwroot\pleasanter\App_Data\Parameters にあるファイルが対象
Server=tcp:(local),1433; の部分を Server=tcp:(192.168.50.1),1433; のようにLinuxサーバのIPアドレスに書き換える。
※この時、Windowsでのセットアップが済んでいるため、それぞれPWDの値が入っていますが、それでよかったでしょうか？

２．definition_Sql.xlsmを上書きコピーする。
Windows側の %SystemDrive%\inetpub\wwwroot\pleasanter\App_Data\Definitions にあるファイルが対象
githubから取ってきたImplem.Pleasanter.NetCore\Implem.Pleasanter\App_Data\Definitionsにあるファイルを使って、Windows側へ上書きコピー

３．テーブル自動構成プログラムを動かし、Linux側のSQL Serverへ初期データベースを構成する。
具体的には、Windows側のコマンドプロンプト（管理者権限）にて、以下のコマンドをたたく。
Implem.CodeDefiner.exe _rds /p %SystemDrive%\inetpub\wwwroot\pleasanter /s /r

以下のようなエラーが出力されます。

[11001] SQL Server への接続を確立しているときにネットワーク関連またはインスタンス固有のエラーが発生しました。サーバーが 見つからないかアクセスできません。インスタンス名が正しいこと、および SQL Server がリモート接続を許可するように構成されていることを確認してください。 (provider: TCP Provider, error: 0 - そのようなホストは不明です。)

IPアドレスでの指定はできないのでしょうか？（もしくは指定の仕方が間違っている？）
pingが飛ぶことと、ManagementStudioでは接続できていることから、FWなどの問題ではなさそうです。ご教授いただけないでしょうか。

**Comment by koikoi0407** [comment]
私も同じところでエラーになりました。
Server=tcp:(192.168.50.1)のカッコを外してみて下さい。
Server=tcp:192.168.50.1
私はこれで解決しました。

**Comment by jakenjarvis** [comment]
@koikoi0407 さん、ありがとうございます！
それ試してみたんだけどなぁ・・・と思いながらやってみたら、すんなり動きました（汗）
どうやら、私が試したときは、「tcp:」まで消してしまっていたようです。

こちらの修正ミスでしたので、このissueはクローズしますね。
