### ISSUE TITLE
一覧表示にコメントが表示されない

### ISSUE THREAD

**Issue by funakura** [Implem/Implem.Pleasanter.NetCore#29]
「Pleasanter.NetCore_1.1.12.2.zip」では、一覧表示でコメントの内容が表示されていました。
しかし、「Pleasanter.NetCore_1.1.13.0.zip」「Pleasanter.NetCore_1.1.13.0.zip」では、一覧表示にコメントの内容が表示されません。
これは不具合・仕様変更のどちらでしょうか？

**Comment by funakura** [comment]
訂正：「Pleasanter.NetCore_1.1.13.0.zip」「Pleasanter.NetCore_1.1.14.0.zip」で、一覧表示にコメントが表示されません。

**Comment by m-ishikawa1980** [comment]
コメントのパラメータを追加して、バージョンアップの際に古い
パラメータファイルで上書きしたためにゼロ件となっていることが想定されます。
パラメータの設定を確認いただけますでしょうか。

**Comment by funakura** [comment]
ご指摘の通りパラメータファイルが古かったです。
パラメータファイルの置き換えでミスしていました。お手数をおかけして申し訳ありません。

回答ありがとうございました。
