### ISSUE TITLE
テーブル自動構成プログラム（CodeDefiner）のビルドと実行について

### ISSUE THREAD

**Issue by jakenjarvis** [Implem/Implem.Pleasanter.NetCore#3]
**Ubuntu 18.04にて、「テーブル自動構成プログラム（CodeDefiner）」のビルドと実行が動作しました** ので、ご報告します。
これによって、Windows IISの環境構築作業が不要になるので、ずいぶん楽になります。

「Linux版インストーラー」の準備が整うまで、 **Windows開発環境でpublishしたファイル一式を、バージョン毎に公式でzipダウンロード** できるようにしてもらえると、利用者はLinuxだけで完結できそうなので、検討して頂けると嬉しいです。

# 前置き
Implem.Pleasanter.NetCore 1.0.0（2018/09/15）時点で、linuxで動かすためには、
・Pleasanter開発環境（Windows必須）
・Pleasanter動作環境（WindowsIIS必須）
の２つの環境が別途必要でしたが、とりあえず「Pleasanter開発環境(Windows必須)」のみにできました。
確認した環境は、Ubuntu 18.04ですが、他のディストリビューションでも同じ方法で行けると思います。

# WindowsのVisual Studio 2017でpublishしたフォルダをLinux側の設置フォルダへコピー
VisualStudioの発行処理で、publishフォルダは以下の位置に生成される。（プロジェクトルートフォルダは各自の環境に置き換えてみて下さい）
C:\Users\<username>\Implem.Pleasanter.NetCore\Implem.Pleasanter\bin\Debug\netcoreapp2.1\publish
※ReleaseビルドなのにDebugに出力される不思議。

※ここでは `` /opt/Implem.Pleasanter.NetCore/ `` の直下に `` App_Data `` や `` ja `` フォルダ、 `` Implem.Pleasanter.dll `` などがくるように配置する。

``
$ sudo cp -r ./publish/ /opt/Implem.Pleasanter.NetCore/
``

権限変更（適切な権限を要検討）※書き込み権限がないとエラーになる。
``
$ sudo chmod -fR 777 /opt/Implem.Pleasanter.NetCore/
``

# CodeDefinerのビルド
ログインユーザのHomeフォルダ内に `` git clone `` して、そこでCodeDefinerのみビルドします。

```
$ sudo apt install -y git

$ cd
$ git clone https://github.com/Implem/Implem.Pleasanter.NetCore.git

$ cd ~/Implem.Pleasanter.NetCore/
$ sudo dotnet build ./Implem.CodeDefiner/Implem.CodeDefiner.csproj --runtime linux-x64 --framework netcoreapp2.1
```

# CodeDefinerの実行
ビルドで作成した `` Implem.CodeDefiner.dll `` をdotnetコマンドで実行します。パラメータは、 [プリザンターのデータベースを手動で構成する（高度な設定）Rev: a4c9965](https://github.com/Implem/Implem.Pleasanter/wiki/%E3%83%97%E3%83%AA%E3%82%B6%E3%83%B3%E3%82%BF%E3%83%BC%E3%81%AE%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E3%82%92%E6%89%8B%E5%8B%95%E3%81%A7%E6%A7%8B%E6%88%90%E3%81%99%E3%82%8B%EF%BC%88%E9%AB%98%E5%BA%A6%E3%81%AA%E8%A8%AD%E5%AE%9A%EF%BC%89/a4c99657f98e3a8dd3e338b13866e5e80055ffba) を参考にします。
環境によっては、 `` /opt/Implem.Pleasanter.NetCore/App_Data/Parameters/Service.json `` や `` /opt/Implem.Pleasanter.NetCore/App_Data/Parameters/Rds.json `` を修正してから実行します。
仮想環境で試用目的の場合は、修正の必要はないです。

```
$ cd /opt/Implem.Pleasanter.NetCore/
$ sudo dotnet ~/Implem.Pleasanter.NetCore/Implem.CodeDefiner/bin/Debug/netcoreapp2.1/linux-x64/Implem.CodeDefiner.dll _rds /p /opt/Implem.Pleasanter.NetCore/ /s /r
```

※dotnetコマンドでDLLを実行するには、作業対象がカレントフォルダでないとダメな場合があるみたいです。

以下、実行結果

```
[sudo] <username> のパスワード: 
Please enter the SA password.
************
<INFO> RdsConfigurator.Configure: Implem.Pleasanter
<INFO> LoginsConfigurator.Execute: Implem.Pleasanter_Owner
<INFO> LoginsConfigurator.Execute: Implem.Pleasanter_User
<INFO> TablesConfigurator.ConfigureTableSet: Tenants
<INFO> TablesConfigurator.ConfigureTableSet: Demos
<INFO> TablesConfigurator.ConfigureTableSet: SysLogs
<INFO> TablesConfigurator.ConfigureTableSet: Statuses
<INFO> TablesConfigurator.ConfigureTableSet: ReminderSchedules
<INFO> TablesConfigurator.ConfigureTableSet: Healths
<INFO> TablesConfigurator.ConfigureTableSet: Depts
<INFO> TablesConfigurator.ConfigureTableSet: Groups
<INFO> TablesConfigurator.ConfigureTableSet: GroupMembers
<INFO> TablesConfigurator.ConfigureTableSet: Users
<INFO> TablesConfigurator.ConfigureTableSet: LoginKeys
<INFO> TablesConfigurator.ConfigureTableSet: MailAddresses
<INFO> TablesConfigurator.ConfigureTableSet: OutgoingMails
<INFO> TablesConfigurator.ConfigureTableSet: SearchIndexes
<INFO> TablesConfigurator.ConfigureTableSet: Items
<INFO> TablesConfigurator.ConfigureTableSet: Sites
<INFO> TablesConfigurator.ConfigureTableSet: Orders
<INFO> TablesConfigurator.ConfigureTableSet: ExportSettings
<INFO> TablesConfigurator.ConfigureTableSet: Links
<INFO> TablesConfigurator.ConfigureTableSet: Binaries
<INFO> TablesConfigurator.ConfigureTableSet: Permissions
<INFO> TablesConfigurator.ConfigureTableSet: Issues
<INFO> TablesConfigurator.ConfigureTableSet: Results
<INFO> TablesConfigurator.ConfigureTableSet: Wikis
<SUCCESS> Starter.ConfigureDatabase: Database configuration is complete.
<INFO> PerformanceCollection.Save: 
      7,965.6661	Main
      7,655.1314	ConfigureDatabase
<SUCCESS> Starter.Main: All of the processing has been completed.
```

---

# 本当はpublishもLinux側でやりたい！
Windowsを使わずにlinux上でセットアップしたいが、dotnet publishができない。（publishに関しては、Implemさんもこの結論にたどり着いていると思いますが、やっぱりどうにかしたいですね）

dotnet publishコマンドを使って、PleasanterNetCore.slnを対象にLinux向けの発行処理を行うには、以下のようなコマンドで行けそうでした。

```
$ sudo dotnet publish --configuration Release --manifest PleasanterNetCore.sln --runtime linux-x64 --framework netcoreapp2.1 --self-contained --output /opt/Implem.Pleasanter.NetCore/
```

ですが、dotnetコマンド自体がnetstandard2.0とnetcoreapp2.1の「混在sln」を一発でpublishできない様子です。
（Windowsでコマンド叩いてもできなかったので、dotnetコマンドのLinux対応の問題というより、dotnetコマンドの機能不足の問題だと思う）

ただ、csproj単位でのdotnet buildは通せる模様です。 ~~dotnetコマンドの改善を待たずに何とかしたい場合は、個別にビルドして、手動でpublish後のフォルダ構成まで構築すればWindows開発環境も不要にできるかも？~~

参考までに、プロジェクト単位のビルドは、以下のコマンドで通せました。
（ただ、エラーは出なくても、警告がいっぱいでるので、何か機能不全になっているかもしれません）

```
$ cd ~/Implem.Pleasanter.NetCore/
$ sudo dotnet build ./HttpWrappers/HttpWrappers.csproj --runtime linux-x64 --framework netstandard2.0
$ sudo dotnet build ./Implem.DefinitionAccessor/Implem.DefinitionAccessor.csproj --runtime linux-x64 --framework netstandard2.0
$ sudo dotnet build ./Implem.DisplayAccessor/Implem.DisplayAccessor.csproj --runtime linux-x64 --framework netstandard2.0
$ sudo dotnet build ./Implem.ParameterAccessor/Implem.ParameterAccessor.csproj --runtime linux-x64 --framework netstandard2.0
$ sudo dotnet build ./Stub/Stub.csproj --runtime linux-x64 --framework netstandard2.0
$ sudo dotnet build ./Implem.Libraries/Implem.Libraries.csproj --runtime linux-x64 --framework netstandard2.0
$ sudo dotnet build ./Implem.CodeDefiner/Implem.CodeDefiner.csproj --runtime linux-x64 --framework netcoreapp2.1
$ sudo dotnet build ./Implem.Pleasanter/Implem.Pleasanter.csproj --runtime linux-x64 --framework netcoreapp2.1
```

slnのビルドも以下で通りました。ただ、CodeDefiner以外は動かしていないので、Pleasanterがまともに動くかどうかは分かりません・・・。

``
sudo dotnet build ./PleasanterNetCore.sln --runtime linux-x64
``

ちなみに、これに `` --framework netcoreapp2.1 `` を付けるとエラーでビルド出来なくなります。
なので、 `` dotnet publish `` も `` --framework netcoreapp2.1 `` を外してやってみましたが、ダメでした。そんなに甘くなかったです。

ということで、ここから先は、Implemさんに頑張って対応して頂きたいです。
LinuxでのPleasanter導入検討中ですので、素早い対応を期待しています。
取り急ぎ、情報提供まで。

**Comment by implem-ishizaki** [comment]
Issueありがとうございます。
最新版ではCodeDefinerもLinux(dotnetコマンド)でビルド/動作するようになりました。
Linuxだけでビルドするという項目を README に追加いたしました。
https://github.com/Implem/Implem.Pleasanter.NetCore#linux-%E3%81%A0%E3%81%91%E3%81%A7%E3%83%93%E3%83%AB%E3%83%89%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B
是非ご確認ください。
