### ISSUE TITLE
検索で文字化け

### ISSUE THREAD

**Issue by jakenjarvis** [Implem/Implem.Pleasanter.NetCore#4]
ubuntu 18.04
ログイン後、画面右上の検索ボックスに文字を入力し、Enterで検索開始すると、文字化けした文字で検索され、該当するデータがあっても0件になりました。

「テスト」と入力し、Enterを押した後の画面のスクリーンショットを以下に添付します。
![kensaku_mojibake](https://user-images.githubusercontent.com/211344/45587632-4c5e5c80-b943-11e8-897c-fcd01d7cccbb.png)

**Comment by implem-ishizaki** [comment]
Issueありがとうございます。
最新版では検索ボックスへの入力が文字化けしなくなりました。
是非ご確認ください。
