### ISSUE TITLE
テーブルの項目を削っても表示される項目がある

### ISSUE THREAD

**Issue by jakenjarvis** [Implem/Implem.Pleasanter.NetCore#5]
ubuntu 18.04
以下の手順で限界まで項目を削ったテーブルを作成すると、削ったにも関わらず一覧表に表示される項目がある。
（項目を削れることが問題なのか、削ったのに表示されるのが問題なのか分かりませんが・・・）

１．記録テーブルを新規作成する。
２．「管理→テーブルの管理」の「エディタ」にて、IDとバージョンだけにして、他の項目をすべて無効化する。（IDとバージョンのみ無効化できなかった）
３．「更新」する。
４．該当の記録テーブルを「表示→一覧」にすると、「タイトル/内容」「コメント」「状況」などが表示される。

**Comment by implem-ishizaki** [comment]
Issueありがとうございます。
プリザンターではエディタの項目と一覧の項目の表示設定は「テーブルの管理」に個別の設定(タブ)がございます。
一覧に表示する項目は「一覧」タブでの設定をお試しください。
是非ご確認ください。
