### ISSUE TITLE
サーバスクリプトelementsオブジェクトの挙動について

### ISSUE THREAD

**Issue by tacker-oh** [Implem/Implem.Pleasanter.NetCore#55]
サーバスクリプトの`elements.DisplayType`について、挙動を教えて頂きたいです。
`elements.DisplayType('CreateCommand', 3)`とした場合、作成ボタンが表示されます。
引数のDisplayTypeを1, 2にした場合も同様です。

これは不具合でしょうか。
それとも、新規作成はナビゲーションメニューを無効にせよということでしょうか。

お忙しいところ恐縮ですが、ご教示いただけますと幸いです。

使用しているバージョンは1.2.12.0になります。

**Comment by kazuca** [comment]
新規作成が許されてはいないのに、新規作成のナビゲーション（＝新規作成画面）が表示されるのはおかしいというのはあると思います。新規作成ができないとするとナビゲーションで止めてしまうのが自然かとは思います。

**Comment by kazuca** [comment]
マニュアルに

> 戻るボタン、作成ボタンには適用できません。

と記載がありますので、いずれにせよ仕様かと。

**Comment by tacker-oh** [comment]
@kazuca 
マニュアルの制限事項を見落としていました。  
ありがとうございます。

**Comment by tacker-oh** [comment]
本Issueをクローズします。
