### ISSUE TITLE
サーバスクリプトitems.Createについて

### ISSUE THREAD

**Issue by tacker-oh** [Implem/Implem.Pleasanter.NetCore#56]
items.Createを実行すると、以下のエラーが出力されます。

```
ERROR: 42P01: missing FROM-clause entry for table "Issues"
at HostDelegate.<anonymous> (<anonymous>)
at Script:32:19
```

これについて、解決策等ご教示いただけますと幸いです。
使用しているバージョンは1.2.12.0ですが、それ以前のバージョンでも同様のエラーを確認しています。

**Comment by YoshikiSawada** [comment]
同様の事象が発生していましたが、バージョン1.2.17.0で解消したことを確認しました。

**Comment by tacker-oh** [comment]
私の手元の環境でも、1.2.17.0でitems.Createが動作することを確認しました。  
ご対応いただきありがとうございました。  
IssueをCloseします。
