### ISSUE TITLE
「SQL Server を構成する（Linux）」について、補足ご説明をお願いします。

### ISSUE THREAD

**Issue by tdhouse** [Implem/Implem.Pleasanter.NetCore#6]
お世話になります。
「SQL Server を構成する（Linux）」について、補足ご説明をお願いします。

1. プリザンターのインストーラー（従来のもの）を使用し、Windows 上にプリザンターを構築します。
2. Linux 上の SQL Server を Windows マシン上から接続できるようにします。
3. PleasanterNetCore\Implem.Pleasanter\App_Data\Parameters\Rds.json ファイルを書き換え、接続先を Linux 上の SQL Server にします。
4. PleasanterNetCore\Implem.Pleasanter\App_Data\Definitions\definition_Sql.xlsm ファイルを .NET Core 版（Linux版）のソースコードのもので上書きします。
5. プリザンターのインストーラーを使用して、Linux 上の SQL Server を構成します。

■1. については「開発環境の構築（Windows）」で実施済みであり、ここで何かするものではないと考えていますが宜しいでしょうか？

■4. の「 .NET Core 版（Linux版）のソースコード」のxlsmはどこで入手できますか？

■3. のjsonファイルは、Pleasanterのインストール資材のzip圧縮された中のことでしょうか？
つまり、zipを解凍→json編集・4.のxlsm差替え→再圧縮してから、5.を実行するという理解でよろしいでしょうか？

宜しくお願いします。

**Comment by implem-ishizaki** [comment]
Issueありがとうございます。
最新版ではLinux上での作業だけでダウンロードしたソースファイルからデータベース初期設定プログラムをビルドし実行できるようになりました。
ダウンロードしたソースファイルの Implem.Pleasanter/App_Data/Parameters/Rds.json 
ファイルのパスワード等を書き換えて README 
のLinuxだけでビルドするという項目を参考にコマンドを実行してください。
https://github.com/Implem/Implem.Pleasanter.NetCore#linux-%E3%81%A0%E3%81%91%E3%81%A7%E3%83%93%E3%83%AB%E3%83%89%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B
是非ご確認ください。
