### ISSUE TITLE
「ビュー」の表示後に「Column 'xxx,ItemTitle' does not belong to table Main.」が発生

### ISSUE THREAD

**Issue by tatsuyasenbom** [Implem/Implem.Pleasanter.NetCore#61]
# 環境
* `Windows 10 Pro`
* `SQL Server 2019 Express`
* `IIS`
* `Pleasanter ver.1.2.22.0`

# 現象
1. 「ビュー」の表示後に「アプリケーションで問題が発生しました。」とフッターにトーストが表示
2. `SELECT Class, ErrMessage, ErrStackTrace FROM SysLogs WHERE Class = 'items' AND ErrMessage IS NOT NULL ORDER BY SysLogId DESC;`にて上記1が発生した際のログを確認
    
    | Class | ErrMessage | ErrStackTrace |
    |:---:|:---:|:---:|
    | items | Column 'ClassA~24129,ItemTitle' does not belong to table Main. | at System.Data.DataRow.GetDataColumn(String columnName)\r\n   at System.Data.DataRow.get_Item(String columnName)\r\n   at Implem.Pleasanter.Libraries.Settings.SiteSettings.LinkedChoice(Context context, Column column, DataRow dataRow, Link link) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\Settings\SiteSettings.cs:line 3596\r\n   at Implem.Pleasanter.Libraries.Settings.SiteSettings.<>c__DisplayClass300_1.<SetChoiceHash>b__7(DataRow dataRow) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\Settings\SiteSettings.cs:line 3575\r\n   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()\r\n   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()\r\n   at Implem.Libraries.Utilities.Linqs.ForEach[T](IEnumerable`1 source, Action`1 action) in C:\Implem\Pleasanter.NetCore\Implem.Libraries\Utilities\Linqs.cs:line 11\r\n   at Implem.Pleasanter.Libraries.Settings.SiteSettings.<>c__DisplayClass300_0.<SetChoiceHash>b__1(Column column)\r\n   at Implem.Libraries.Utilities.Linqs.ForEach[T](IEnumerable`1 source, Action`1 action) in C:\Implem\Pleasanter.NetCore\Implem.Libraries\Utilities\Linqs.cs:line 13\r\n   at Implem.Pleasanter.Libraries.Models.GridData.Get(Context context, SiteSettings ss, View view, TableTypes tableType, SqlColumnCollection column, SqlJoinCollection join, SqlWhereCollection where, Int32 top, Int32 offset, Int32 pageSize, Boolean count) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\Models\GridData.cs:line 128\r\n   at Implem.Pleasanter.Libraries.Models.GridData..ctor(Context context, SiteSettings ss, View view, Nullable`1 tableType, SqlColumnCollection column, SqlJoinCollection join, SqlWhereCollection where, Int32 top, Int32 offset, Int32 pageSize, Boolean count) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Libraries\Models\GridData.cs:line 49\r\n   at Implem.Pleasanter.Models.IssueUtilities.GetGridData(Context context, SiteSettings ss, View view, Int32 offset) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:line 200\r\n   at Implem.Pleasanter.Models.IssueUtilities.IndexJson(Context context, SiteSettings ss) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Models\Issues\IssueUtilities.cs:line 180\r\n   at Implem.Pleasanter.Controllers.ItemsController.Index(Context context, Int64 id) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter\Controllers\ItemsController.cs:line 23\r\n   at Implem.Pleasanter.NetCore.Controllers.ItemsController.Index(Int64 id) in C:\Implem\Pleasanter.NetCore\Implem.Pleasanter.NetCore\Controllers\ItemsController.cs:line 28\r\n   at lambda_method854(Closure , Object , Object[] )\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location --- |
3. `ClassA~24129`は本`記録テーブル`に対してリンクしている別`記録テーブル`の`SiteId`

# 確認
* 上記`現象`を回避するため`記録テーブル`間でのリンクで気を付けるべき作法などはございますでしょうか？

**Comment by kazuca** [comment]
こちら発生バージョンはどれでしょうか？
1.2.22.0だと1.2.21.0で問題のないリンクで同じようなエラーが出ていますので、プログラムで何か問題が発生していると推測しています。

**Comment by tatsuyasenbom** [comment]
> こちら発生バージョンはどれでしょうか？ 1.2.22.0だと1.2.21.0で問題のないリンクで同じようなエラーが出ていますので、プログラムで何か問題が発生していると推測しています。

先ほど検証のため構築した`Pleasanter ver.1.2.22.0`で確認しました。

**Comment by uchi-ta** [comment]
該当箇所を修正し1.2.22.1を公開いたしました。

**Comment by tatsuyasenbom** [comment]
> 該当箇所を修正し1.2.22.1を公開いたしました。

ご対応いただきありがとうございました。

c5a2153216da40bb609d755e85a05fa455d2f4d4 にて改善されていることを確認しました。

素早いご対応ありがとうございました :laughing:
