### ISSUE TITLE
ユーザー管理画面が開けない

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter.NetCore#66]
ユーザー管理画面を開こうとすると「不正なリクエストが送信されました。」と表示され、管理画面が正常に表示されません。

発生バージョンは1.2.24.[0-2]です。

**Comment by kazuca** [comment]
デバッグを行ったところ、パラメータの.Service.jsonでShowProfilesをfalseにしていた場合に一覧が表示されなくなるということが確認出来ました。
1/8の差分でUserUtilities.GetByApiが変更されていることによりUserValidators.OnEntryに飛ばれされる条件が変わったことにより発生しているものと思われます。

**Comment by kazuca** [comment]
1.2.25.0で現象が発生しないようになっていることは確認出来ました。
しかし、!68の現象が発生してるため解決できていません。

**Comment by shoheichikura** [comment]
本件、1.2.26.0において、ShowProfilesがfalseの状態でテナント管理者（かつ非特権ユーザ）で同じように表示ができない状態です。
（ナビゲーションメニューの「ユーザーの管理」メニューは表示される）
ユーザー管理ページにアクセスできないのが間違っているのか、ユーザーの管理メニューが表示されるのが間違っているのかどちらかだと思いますが、どちらでしょうか？
