### ISSUE TITLE
非特権ユーザーだとページが空になる

### ISSUE THREAD

**Issue by kazuca** [Implem/Implem.Pleasanter.NetCore#68]
非特権ユーザーでページが空になる現象が発生しています。特権ユーザーでは正常に表示されます。
発生バージョンは1.2.25.0です。

**Comment by tatsuyasenbom** [comment]
私も同様の現象を`Pleasanter.NetCore x Windows Server 2019 x SQL Server 2017 x IIS`確認しました。ただ`特権ユーザ`でなくても`サイトの管理`のチェックのチェック有無で閲覧できることを確認しました。

![image](https://user-images.githubusercontent.com/87968771/149684970-072716ec-476b-47d2-a1d5-8d0f4a7600b1.png)

**Comment by kazuca** [comment]
@tatsuyasenbom さん
情報ありがとうございます。こちらでも追試してみます。

**Comment by tatsuyasenbom** [comment]
> 私も同様の現象を`Pleasanter.NetCore x Windows Server 2019 x SQL Server 2017 x IIS`確認しました。ただ`特権ユーザ`でなくても`サイトの管理`のチェックのチェック有無で閲覧できることを確認しました。
> 
> ![image](https://user-images.githubusercontent.com/87968771/149684970-072716ec-476b-47d2-a1d5-8d0f4a7600b1.png)

* また本症状は、`記録テーブル`や、その上で利用している`ビュー`で発症しました。
* `Wiki`では確認できませんでした。

**Comment by uchi-ta** [comment]
ご指摘の件、サイトの管理の権限を有しないユーザで一覧などが表示できない不具合がございました。修正版 1.2.25.1 を提供いたしました。ご不便おかけして申し訳ございません。

**Comment by tatsuyasenbom** [comment]
早々にご対応いただきありがとうございました。

提供いただいた`1.2.25.1`にて、本症状が改善したことを確認しました。

**Comment by kazuca** [comment]
こちらでも修正されていることが確認できました。
