### ISSUE TITLE
分類の項目連携でエラー

### ISSUE THREAD

**Issue by necobus-issa** [Implem/Implem.Pleasanter.NetCore#7]
下記の URL先を参考に、.NET Core版で分類の項目連携を行いました。
・https://pleasanter.hatenablog.jp/entry/20200228_item_linkage3

ところが、「Bad Request」のエラーが返されてしまいます。
![image](https://user-images.githubusercontent.com/36583642/76602086-954d9c00-654d-11ea-83f7-3932f314c057.png)

デモサイトの方では試したところ問題なく動作しているようです。
・https://pleasanter.azurewebsites.net/

デバッグのスクリーンショットを添付いたします。
![image](https://user-images.githubusercontent.com/36583642/76601611-9fbb6600-654c-11ea-9a40-a2d2a78af699.png)

ソース：「Implem.Pleasanter.NetCore-master\Implem.Pleasanter\Models\Results\ResultUtilities.cs」の 1797行目にある「context.RequestDataString」が空値になっているため、
左辺の api変数が nullとなり、「ApiResponses.BadRequest()」が返却されています。

最新版にて修正がされているようでしたら、Githubにご反映いただけないでしょうか。

よろしくお願いいたします。

**Comment by uchi-ta** [comment]
Issueありがとうございます。最新版にて修正いたしました。
