### ISSUE TITLE
スクリプト 項目の詳細設定で読取専用にした場合に $p.getControl("Owner").val() や $p.getControl("ClassA").val() の戻り値が undefined

### ISSUE THREAD

**Issue by tatsuyasenbom** [Implem/Implem.Pleasanter.NetCore#70]
# 環境
* 1.2.26.2, 12.25.0
* Windows Server 2016
* SQL Server 2017

# 現象
* 記録テーブルに仕込んだスクリプトにて標題の現象を確認
* 当該ページやSQL Server DB 内の該当レコードを見る限り`$p.getControl("項目名").val()`で指定した項目には値が存在しており
* `$("#Issues_Owner").attr("data-value")`などでは値が取得が出来ることを確認

以上です。お手数をおかけしますが、ご確認の程よろしくお願いいたします。

**Comment by tacker-oh** [comment]
#58 とは違うのでしょうか？

**Comment by kazuca** [comment]
マニュアルに記載があります。

https://pleasanter.org/manual/faq-readonly-value

val使えば取得出来ます。

**Comment by tatsuyasenbom** [comment]
> https://github.com/Implem/Implem.Pleasanter.NetCore/issues/58 とは違うのでしょうか？

> マニュアルに記載があります。
> https://pleasanter.org/manual/faq-readonly-value
> valではなくtextを使えば取得出来ます。

ご返信いただきありがとうございます。

現状（`1.2.27.2`）にて、`期限付きテーブル`にて以下`スクリプト`を仕込み`編集`で発火させたところ

```js
console.log($p.getControl('Owner').val());
console.log($p.getControl('Owner').text());
```

![image](https://user-images.githubusercontent.com/87968771/152738981-77cb7480-da54-45d7-b638-eee2b459a139.png)

ならば

```

ユーザ名
```

となり、

![image](https://user-images.githubusercontent.com/87968771/152739223-c0cfd56e-0612-4b7d-804b-8c1007e787d6.png)

ならば

```
UserId
ユーザ名
```

が、それぞれ出力されることを確認しています。

確かに`$p.getControl('Owner').text()`であれば`読取専用`チェックボックスの状態に関わらず出力はされますが、それで得られる結果は`UserId`でなく、上記の設定では`ユーザ名`となります。

現状模索しているのは、`読取専用`チェックボックスが有効でも、`$p.getControl('Owner')`を介して、`担当者（Owner）`と紐づく`UserId`を取得できないかどうかという点です。

**Comment by kazuca** [comment]
``UserId``でしたら``$p.getControl("Owner").data("value")``や``$p.getControl("Owner").attr("data-value")``で取得出来るかと思います。

**Comment by tatsuyasenbom** [comment]
> $p.getControl("Owner").attr("data-value")

ありがとうございます。

`$p.getControl("Owner").val()`の代わりに、`$p.getControl("Owner").data("value")`又は`$p.getControl("Owner").attr("data-value")`で`UserId`が取得できることを確認しました。

`1.2.27.2`時点では、`$p.getControl("Owner").val()`は、非推奨な関数または、本件とは別の用途で利用する関数であるという、理解でよろしいでしょうか？

**Comment by kazuca** [comment]
``$p.getControl("Owner").val()``は非読み取り専用時のみで使用出来るという認識で間違い無いかと思います。

``$p.getControl``は、期限付きテーブル/通常のテーブルのテーブル定義に応じて、変換処理を行っているだけのメソッドです。今回の場合は、``$p.getControl("Owner")``→``$("#Issues_Owner")``の変換を行っています。
そのため、``$p.getControl``を使用してもjQueryで出来る以上のことは出来ないようになっています。

**Comment by tatsuyasenbom** [comment]
> `$p.getControl("Owner").val()`は非読み取り専用時のみで使用出来るという認識で間違い無いかと思います。
> 
> `$p.getControl`は、期限付きテーブル/通常のテーブルのテーブル定義に応じて、変換処理を行っているだけのメソッドです。今回の場合は、`$p.getControl("Owner")`→`$("#Issues_Owner")`の変換を行っています。 そのため、`$p.getControl`を使用してもjQueryで出来る以上のことは出来ないようになっています。

ご回答いただきありがとうございます💦腑に落ちました💦
