### ISSUE TITLE
ShowProfiles:false(Service.json)でもテナント管理者にはナビゲーションメニューにユーザー管理メニューが表示される

### ISSUE THREAD

**Issue by shoheichikura** [Implem/Implem.Pleasanter.NetCore#71]
タイトルの件、ソースコードを確認してみました。
※前提としてShowProfilesは一般ユーザに限らず、テナント管理者なども含め、非特権ユーザすべてに影響を及ぼす設定との理解でおります。
　（Implem.Pleasanter.Models.UserValidators:38の前に当該の判定があることからそのように判断しました）
　もし、一般ユーザに対してプロファイルを表示させないような目的の設定であれば修正箇所が異なってくる認識です。

Implem.Pleasanter.Libraries.HtmlNavigationMenu.cs:334において、
`var canManageUsers = Permissions.CanManageTenant(context: context);`
とあり、同ファイル:366にて、
`case "SettingsMenu_UserAdmin":`
`return canManageUsers;`
とあるため、ユーザ管理メニューは非特権ユーザでもテナント管理者であれば表示される状態です。

ところが、Implem.Pleasanter.Models.UserValidators:34において、
`if (!Parameters.Service.ShowProfiles && !context.HasPrivilege)`
としてしまっているため、特権ユーザでないテナント管理者がユーザー管理メニューは表示されるにもかかわらず、
ユーザー管理画面が開けない状態となってしまっています。

Implem.Pleasanter.Libraries.HtmlNavigationMenu.cs:366は
`return ((canManageUsers && Parameters.Service.ShowProfiles) || context.HasPrivilege);`
となるべきではないでしょうか？
また、同:359についても、
`|| ((canManageUsers && Parameters.Service.ShowProfiles) || context.HasPrivilege);`
となるかと思います。

なお、類似点として、同:389についても
`return Parameters.Service.ShowProfiles || context.HasPrivilege;`
となるかと思います。
（こちらは設定としてプロファイル非表示なのだからここではメニュー非表示としておき、表示するのはユーザ一覧から、という方針であればその限りではありません）

**Comment by uchi-ta** [comment]
ご指摘ありがとうございます。ShowProfilesがfalseの際にテナント管理者で利用できないメニューが表示される問題について修正を検討いたします。

**Comment by shoheichikura** [comment]
ご対応ありがとうございました。
1.2.27.0の以下にて修正されていることが確認できました。
・Service.jsonのShowProfilesがfalseの際にテナント管理者のメニューが正しく表示されない問題を解消。
