### ISSUE TITLE
Mail が送信されません（Pleasanter_1.3.0.1）

### ISSUE THREAD

**Issue by funakura** [Implem/Implem.Pleasanter.NetCore#79]
Ubuntu + Dockerコンテナで構築したPleasanter 1.13.0.1でmailが送信されません。
1.13.0.1のコメントがSMTP送信改善でしたので報告します。

ベースイメージ：mcr.microsoft.com/dotnet/sdk:6.0-focal
Pleasanter：1.13.0.1
DB：PostgreSQL 12
Mail.json
{
    "SmtpHost": "XXXXXX",
    "SmtpPort": 25,
    "SmtpUserName": null,
    "SmtpPassword": null,
    "SmtpEnableSsl": false,
    "FixedFrom": null,
    "AllowedFrom": null,
    "SupportFrom": "XXXXX",
    "InternalDomains": "XXXX"
}

**Comment by funakura** [comment]
症状は以下です。
Pleasanterの画面上は「メールを送信しました」と表示されます。
SMTPサーバ側のログなどは確認していません。
データベースは[Pleasanter_1.2.29.2](https://github.com/Implem/Implem.Pleasanter.NetCore/releases/tag/Pleasanter_1.2.29.2)が稼働していたDBを使っています。ParametersはPleasanter 1.13.0.1の物を変更した物を使用しています。
同じDBと設定でPleasanter_1.2.29.4に変更するとMail送信・到着することを確認しています。

**Comment by funakura** [comment]
承認情報のnull指定が原因でした。
以下の変更でメールの送信を確認しました。

ファイル：Implem.Pleasanter.NetCore\Implem.Pleasanter\Libraries\DataSources\Smtp.cs
106行
//if (Parameters.Mail.SmtpUserName != null &&
//    Parameters.Mail.SmtpPassword != null)
if( string.IsNullOrEmpty(Parameters.Mail.SmtpUserName) == false &&
string.IsNullOrEmpty(Parameters.Mail.SmtpPassword) == false)

以上、反映いただけると助かります。

**Comment by uchi-ta** [comment]
ご指摘のとおり不具合がございました。1.3.1.1 で解消いたしましたのでバージョンアップをお願い致します。

**Comment by funakura** [comment]
[Pleasanter_1.3.1.1](https://github.com/Implem/Implem.Pleasanter.NetCore/releases/tag/Pleasanter_1.3.1.1)にてメール送信されることを確認しました。
対応ありがとうございます。
感謝いたします。
