### ISSUE TITLE
1.3.x.x on Windows x IIS にてログアウト操作後にトップへ画面遷移してログアウトが処理されない事を確認

### ISSUE THREAD

**Issue by tatsuyasenbom** [Implem/Implem.Pleasanter.NetCore#80]
# 現象
1. 以下`ログアウト`リンクを押下
    * ![image](https://user-images.githubusercontent.com/87968771/157139654-dab53020-58d7-4a0d-a648-99007dc91e33.png)
    * `/pleasanter/users/logout`をURLバーに直打ちしても同じ現象が発生することを確認
2. トップへ遷移
    * ![image](https://user-images.githubusercontent.com/87968771/157139067-1ee63016-cc55-4639-9aeb-37fbcbcca380.png)

# 環境

| No. | 環境 | 結果 |
|:---|:---|:---|
| 1 | Pleasanter 1.3.1.1 on Nginx x Ubuntu 20.04LTS x PostgreSQL 12.9 x .NET 6.0.200 | ログアウトできることを確認 |
| 2 | Pleasanter 1.3.0.1 on IIS x Windows Server 2016 Standard バージョン 1607 OSビルド 14393.4651 x SQL Server 13.0.5103.6 x .NET 6.0.200 | 本現象を確認 |
| 3 | Pleasanter 1.3.1.1 on IIS x Windows Server 2016 Standard バージョン 1607 OSビルド 14393.4651 x SQL Server 13.0.5103.6 x .NET 6.0.200 | 本現象を確認 |
| 4 | Pleasanter 1.3.0.1 on IIS x Windows Server 2019 Standard バージョン 1809 OSビルド 17763.2628 x SQL Server 15.0.2080.9 x .NET 6.0.200 | 本現象を確認 |

**Comment by tatsuyasenbom** [comment]
ちなみに Google Chrome on Windows 11 にて`ログアウト`リンクを押下した後の、クッキーの状態を確認しましたが特に変化はなく、以下クッキーを削除した後、Webブラウザにて画面をリロードすると、ログイン画面へリダイレクトされました。

![image](https://user-images.githubusercontent.com/87968771/157159109-3d77537f-3f80-4730-9d09-f3e23c98b76b.png)

**Comment by uchi-ta** [comment]
pleasanter の仮想ディレクトリ配下で使用している場合に、ログアウトが行えない問題がございました。修正バージョン 1.3.1.2 をリリースいたしましたので、お手数ですがバージョンアップをお願い致します。

**Comment by tatsuyasenbom** [comment]
> pleasanter の仮想ディレクトリ配下で使用している場合に、ログアウトが行えない問題がございました。修正バージョン 1.3.1.2 をリリースいたしましたので、お手数ですがバージョンアップをお願い致します。

ご対応いただきありがとうございました。改善を確認しました。
（確かに仮想ディレクトリを切ってない環境では本現象は発生していませんでした💦）
