### ISSUE TITLE
分類項目で「複数選択」可および「必須入力」としたとき、アラートの表示位置がズレている。

### ISSUE THREAD

**Issue by Kenichiro-NOGI** [Implem/Implem.Pleasanter.NetCore#86]
お世話になっております。
分類項目で「複数選択」かつ「必須入力」としたとき、項目への未入力で作成・更新しようとしたときのアラートの表示位置がズレてしまいます。
確認バージョン：0.50.287.2、1.3.3.0
![image](https://user-images.githubusercontent.com/101759571/160078951-e6cacf4b-2e06-4416-8aeb-2d22bbbaf6f9.png)

**Comment by uchi-ta** [comment]
こちらの不具合を1.3.4.0で修正しました。
