### ISSUE TITLE
Pleasanter 1.3.9.0 期限付きテーブルの分類項目の複数選択を有効にした際、選択したはずの項目が画面上に表示されない。

### ISSUE THREAD

**Issue by tatsuyasenbom** [Implem/Implem.Pleasanter.NetCore#89]
# 環境
* Pleasanter 1.3.9.0 x .NET Core 6.0.5 xWindows Server 2016 x SQL Server 2017

# 現象
* 標題の現象を確認
* `複数選択`を有効にしたときは画面上に選択した項目が表示されない。
    * ![image](https://user-images.githubusercontent.com/87968771/172105152-b0409f74-0549-4077-bb9a-b194f651bbee.png)
    * ![image](https://user-images.githubusercontent.com/87968771/172105554-a1297bfa-7a44-41f8-88fe-8c3083b3e4cc.png)
* `複数選択`を無効にしたときは画面上に選択した項目が表示される。
    * ![image](https://user-images.githubusercontent.com/87968771/172105250-c1cb571c-aabb-4ae6-88fb-8d2334cf3615.png)
    * ![image](https://user-images.githubusercontent.com/87968771/172105513-d59e3729-8fc0-496b-afb7-ad494e7be4b3.png)

**Comment by tatsuyasenbom** [comment]
概要にて報告させていただいた通り、画面にて`複数選択`の`分類A`へ、複数の値を選択・設定し、画面を`更新`した後、画面には表示されませんが、

DB上の当該レコードの`ClassA`には、左記で選択・設定した複数の値が`["121", "16"]`といった形で保持されていることを確認したので、追加で共有させていただきます。

![image](https://user-images.githubusercontent.com/87968771/172575018-fc7f5be6-76c9-49dd-bd24-400c08cb1e53.png)

**Comment by uchi-ta** [comment]
本件、不具合であることを確認しました。1.3.9.1で修正いたしました。

**Comment by tatsuyasenbom** [comment]
早々にご対応いただき、ありがとうございました。

1.3.9.1で本現象が改善している事を確認しました。
